version: 2.1

jobs:
  build_ios:
    macos: 
      xcode: 13.4.1
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - run: echo "Starting to build for iOS"

  build_android_docker_image:
    machine:
      image: ubuntu-2204:2022.07.1
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: docker build -t gotham_android gotham-client/docker_images/android/
      - run:
          name: Login to docker registry
          command: docker login --username "${DOCKER_REG_USERNAME}" --password "${DOCKER_REG_PASSWORD}" "${DOCKER_REG_HOST}"
      - run:
          name: Set Tags
          command: docker tag gotham_android:latest "${DOCKER_REG_HOST}"/"$DOCKER_REG_USERNAME"/gotham_android:latest
      - run:
          name: Push Image
          command: docker image push  --all-tags "${DOCKER_REG_HOST}"/"$DOCKER_REG_USERNAME"/gotham_android

  build_android:
    docker:
      - image: matanzengo/gotham_android:latest
    resource_class: xlarge
    steps:
      - checkout 
      - run: 
          name: Build Debug Version
          command: |
            cd gotham-client 
            cargo ndk -p "${MIN_SDK_VERSION}" -t arm64-v8a -t armeabi-v7a -t x86_64 -o ./jniLibs_debug build 
      - run: 
          name: Build Release Version
          command: |
            cd gotham-client  
            cargo ndk -p "${MIN_SDK_VERSION}" -t arm64-v8a -t armeabi-v7a -t x86_64 -o ./jniLibs build --release
      - store_artifacts:
          path: gotham-client/jniLibs
          destination: gotham-android-release
      - store_artifacts:
          path: gotham-client/jniLibs_debug 
          destination: gotham-android-debug

workflows:
  build_docker_image:
    jobs:
      - build_android_docker_image
  build_ios:
    jobs:
      - build_ios
  build_android:
    jobs:
      - build_android