# "local" or "aws"
db = "local"
# if db = aws (also set environment variables AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY):
# aws_region =

# To enable local DynamoDB use configuration below
# see: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.html
#aws_region = "local"
#local_dynamodb_endpoint = "http://localhost:9000"

region = "" # Override with ENV variable!
pool_id = "" # Override with ENV variable!
issuer = "" # Override with ENV variable!
audience = "" # Override with ENV variable!
