name: Gotham client android/ios lib build

on:
  push:
    branches:
      - master
    paths:
      - "gotham-client/**"
  pull_request:
    branches:
      - master
    paths:
      - "gotham-client/**"

jobs:
  build ios:
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: xcode and macos latest
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Install ios lib
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
        run: rustup target add aarch64-apple-ios && cd gotham-client && cargo rustc --crate-type staticlib --target aarch64-apple-ios --lib && cargo rustc --crate-type staticlib --target aarch64-apple-ios --release --lib

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: gotham-ios-debug/libclient_lib.a
          path: target/aarch64-apple-ios/debug/libclient_lib.a

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: gotham-ios-release/libclient_lib.a
          path: target/aarch64-apple-ios/release/libclient_lib.a

  build_android:
    runs-on: ubuntu-latest
    container:
        image: zengo/gothamclient_androidcontainer:latest
        credentials:
        username: ${{ DOCKER_HUB_USER }}
        password: ${{ DOCKER_HUB_TOKEN }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install android libs
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
        run: cd gotham-client && cargo ndk -p "${MIN_SDK_VERSION}" -t arm64-v8a -t armeabi-v7a -t x86_64 -o ./jniLibs_debug build && cargo ndk -p "${MIN_SDK_VERSION}" -t arm64-v8a -t armeabi-v7a -t x86_64 -o ./jniLibs build --release

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: gotham-client/jniLibs
          path: gotham-android-release

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: gotham-client/jniLibs_debug
          path: gotham-android-debug